language: java

jdk:
 - oraclejdk7

install:
 - sudo apt-get install sshpass -qq
 - sudo apt-get install nsis -qq

env:
  global:
    secure: DtUWKzELlEvNm9MojN8I+wFGY8QSwnbAFBGNXQeFWsxZBOUO7Y7p5d5rEKEYqaPEi0r5pOpfq75ErSmgRz922GD4IjRYuGqhprOzNwRhFMbkBrSkAwZT15dJq+v3RJmBvHi8NNCTaLCNQXvoHgq+mUSIeUMYomMxTSezcTfKWYA=

before_script:
  - echo -e "Host zpserver.info\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_script:
  - sshpass -p "$pass" scp -v *gz lsts@zpserver.info:~/public_html/neptus/Neptus_`git log --pretty=format:%ad_%h --date=short -1`.tar.gz
  - sshpass -p "$pass" scp -v *exe lsts@zpserver.info:~/public_html/neptus/Neptus_`git log --pretty=format:%ad_%h --date=short -1`.exe

